version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/pet_db
      SPRING_DATASOURCE_URL: jdbc:postgresql://monorail.proxy.rlwy.net:57641/railway
      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_PASSWORD: VlhTrnXiKquqehKtXgnnfAbqMzERwwhq
    depends_on:
      - db
  db:
    image: postgres:14.11
    environment:
      DATABASE_PORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pet_db
    expose:
      - 5433